version: "3.9"

services:

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: db
    volumes:
      - ./db/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    restart: always

  web:
    build: ./pymongo
    container_name: flask
    restart: always
    ports:
      - "5000:5000"

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
